# kubectl apply -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  ports:
    - port:  8000
      targetPort:  8000
      nodePort:  30000
  selector:
    app: fastapi